name: test-expr

on:
  push:

jobs:
  test-expr:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: execute_expr
        run: |
          echo ${{ steps.checkout.outcome == 'success' }}
      -
        name: echo_hi
        if: ${{ steps.execute_expr.output }}
        run: |
          echo ${{ steps.execute_expr.output }}
          echo ${{ steps.execute_expr.outcome }}
          echo "hello_world"
