name: test-expr

on:
  push:

jobs:
  is-echo-hi:
    runs-on: ubuntu-latest
    outputs:
      is_echo_hi: ${{ true }}
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

  test-expr:
    runs-on: ubuntu-latest
    needs: is-echo-hi
    steps:
      -
        name: echo_hi
        if: ${{ needs.is-echo-hi.outputs.is_echo_hi }}
        run: |
          echo "hi"
      -
        name: echo_something_else
        if: ${{ !needs.is-echo-hi.outputs.is_echo_hi }}
        run: |
          echo "something else"
